# Configuration pour daedalus.elyon.younity-mc.fr
server {
    server_name daedalus.elyon.younity-mc.fr;

    root /var/www/elyon/daedalus;
    index index.php index.html index.htm;

    # Gestion des API
    location /api/ {
        # Spécifiez le fichier CGI
        fastcgi_param SCRIPT_FILENAME /game/bin/index.cgi;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # Passer la requête au socket fcgiwrap
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        include fastcgi_params;
    }

    # Gestion des fichiers PHP
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;

        # Si l'URL se termine par un /, on enlève le / automatiquement
        rewrite ^/(.+)/$ /$1 permanent;

        # Redirection vers la page de création de niveau
        rewrite ^/levels?/create$ /create last;

        # Redirection vers la page de création de niveau
        rewrite ^/levels?/(.+)/edit$ /create?id=$1 last;

        # Redirection vers la page de suppression de niveau
        rewrite ^/levels?/(.+)/delete$ /util/deleteLevel.php?id=$1 last;

        # Redirection d'URL pour la page de jeu
        rewrite ^/(level|adventure)s?/([^/]+)/play$ /play?id=$2&mode=$1 last;

        # Redirection d'URL pour le mode infini
        rewrite ^/infinite/play$ /play?mode=infinite last;

        # Redirection vers la page de présentation du niveau
        rewrite ^/levels?/(.+)$ /level?id=$1 last;

        # Redirection vers la page de profil
        rewrite ^/profile/(.+)$ /profile?id=$1 last;

        # Ajoute l'extension .php aux fichiers (si ce n'est pas un dossier ou un fichier existant)
        rewrite ^/([^.]+)$ /pages/$1.php last;
    }


    # Protection des fichiers cachés
    location ~ /\.ht {
        deny all;
    }

    listen 443 ssl; # Géré par Certbot
    ssl_certificate /etc/letsencrypt/live/daedalus.elyon.younity-mc.fr/fullchain.pem; # Géré par Certbot
    ssl_certificate_key /etc/letsencrypt/live/daedalus.elyon.younity-mc.fr/privkey.pem; # Géré par Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # Géré par Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # Géré par Certbot
}
