location / {
        try_files $uri $uri/ /index.php?$query_string;
        rewrite ^(.+)/$ $1;

        rewrite ^levels?/create$ /create;
        rewrite ^levels?/(.+)/edit$ /create?id=$1;
        rewrite ^levels?/(.+)/delete$ /util/deleteLevel.php?id=$1;
        rewrite ^(level|adventure)s?/([^/]+)/play$ /play?id=$2&mode=$1;
        rewrite ^infinite/play$ /play?mode=infinite;
        rewrite ^levels?/(.+)$ /level?id=$1;
        rewrite ^profile/(.+)$ /profile?id=$1;

        rewrite ^/([^.]+)$ /pages/$1.php last;
    }

location /levels/create {
    
}